name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ".github/scripts/go"
    steps:
      - name: Checkout repository and branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ${{ github.workspace }}/.github/scripts/go/go.mod
          cache-dependency-path: ${{ github.workspace }}/.github/scripts/go/go.sum
          check-latest: true
          cache: true

      - name: Validate data and format JSON
        run: |
          ROOT_DIR=${{ github.workspace }} go run cmd/yacar_ci.go

      - name: Check for changes
        id: diff
        run: |
          cd ${{ github.workspace }}
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.diff.outputs.changed == 'true'
        run: |
          cd ${{ github.workspace }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[bot] auto-format files"
          git push

  automerge:
    runs-on: ubuntu-latest
    needs: [validate]
    if: |
      github.event_name == 'pull_request' && 
      github.repository == 'coinhall/yacar'
    steps:
      - name: auto-merge
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_FILTER_AUTHOR: "yacarbot[bot]"
          MERGE_LABELS: "status: done"
          MERGE_METHOD: "squash"
          UPDATE_LABELS: "status: done"
          UPDATE_METHOD: "rebase"
