name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ".github/scripts"
    steps:
      - name: Checkout repository and branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.17.1
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install prod dependencies
        run: pnpm install --prod

      - name: Validate chain data
        run: |
          ROOT_DIR=${{ github.workspace }} pnpm validate

  format:
    needs: [validate]
    if: |
      github.repository == github.event.pull_request.head.repo.full_name || 
      github.repository != 'coinhall/yacar'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ".github/scripts"
    steps:
      - name: Checkout repository and branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Install Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.17.1
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install prod dependencies
        run: pnpm install --prod

      - name: Format all json
        run: |
          ROOT_DIR=${{ github.workspace }} pnpm format

      - name: Check for changes
        id: diff
        run: |
          cd ${{ github.workspace }}
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.diff.outputs.changed == 'true'
        run: |
          cd ${{ github.workspace }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[bot] auto-format files"
          git push

  automerge:
    runs-on: ubuntu-latest
    needs: [validate, format]
    if: |
      github.event_name == 'pull_request' && 
      github.repository == github.event.pull_request.head.repo.full_name &&
      github.repository == 'coinhall/yacar' &&
      github.event.pull_request.user.login == 'test'
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: "${{ secrets.MERGE_TOKEN }}"
          MERGE_LABELS: "status: done"
          MERGE_METHOD: "squash"
          UPDATE_METHOD: "rebase"
