# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Validate data and format JSON
        id: validate
        run: |
          ROOT_DIR=${{ github.workspace }} ./format.sh
          echo "status=$?" >> $GITHUB_OUTPUT

      - name: Check for changes
        if: steps.validate.outputs.status == '0'
        id: diff
        run: |
          cd ${{ github.workspace }}
          git diff --quiet . || (echo "Did you forget to run the latest 'format.sh' script?" && exit 1)

      - name: Add comment on PR
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Oops... it looks like something went wrong with the validation of your changes. To help us review your changes faster so that it displays on the website sooner, please run the latest \`format.sh\` (Mac/Linux) /\`format.bat\` (Windows) script!"
            })

  automerge:
    runs-on: ubuntu-latest
    needs: [validate]
    if: |
      github.event_name == 'pull_request' && 
      github.repository == 'coinhall/yacar'
    steps:
      - name: auto-merge
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_FILTER_AUTHOR: "yacarbot[bot]"
          MERGE_LABELS: "status: done"
          MERGE_METHOD: "squash"
