name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Validate data and format JSON
        id: validate
        run: |
          ROOT_DIR=${{ github.workspace }} ./format.sh
          echo "status=$?" >> $GITHUB_OUTPUT

      - name: Check for changes
        if: steps.validate.outputs.status == '0'
        id: diff
        run: |
          cd ${{ github.workspace }}
          git diff --quiet . || (echo "Did you forget to run the latest 'format.sh' script?" && exit 1)

      - name: Add comment on PR
        if: failure()
        run: |
          COMMENT="Oops... It looks like you forgot to run the latest \`format.sh\` (Mac/Linux) /\`format.bat\` (Windows) script. This allows us to review the changes quicker so that it displays on the website sooner!"
          curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"body": "'"$COMMENT"'"}' "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

  automerge:
    runs-on: ubuntu-latest
    needs: [validate]
    if: |
      github.event_name == 'pull_request' && 
      github.repository == 'coinhall/yacar'
    steps:
      - name: auto-merge
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_FILTER_AUTHOR: "yacarbot[bot]"
          MERGE_LABELS: "status: done"
          MERGE_METHOD: "squash"
